version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "Tak1wa"
github_repo = "hoge1017sam"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[hoge-stage1]
[hoge-stage1.pipeline_bootstrap]
[hoge-stage1.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::550669467088:role/aws-sam-cli-managed-hoge-sta-PipelineExecutionRole-Z6EJDGEH3Q8P"
cloudformation_execution_role = "arn:aws:iam::550669467088:role/aws-sam-cli-managed-hoge-CloudFormationExecutionR-313X2II10DYF"
artifacts_bucket = "aws-sam-cli-managed-hoge-stage1-p-artifactsbucket-i9vxs75sivey"
image_repository = ""
region = "ap-northeast-1"

[hoge-stage2]
[hoge-stage2.pipeline_bootstrap]
[hoge-stage2.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::550669467088:role/aws-sam-cli-managed-hoge-sta-PipelineExecutionRole-8CMI2GOGG3X1"
cloudformation_execution_role = "arn:aws:iam::550669467088:role/aws-sam-cli-managed-hoge-CloudFormationExecutionR-L6ENO5FENT4R"
artifacts_bucket = "aws-sam-cli-managed-hoge-stage2-p-artifactsbucket-m4iqdqi8p6xk"
image_repository = ""
region = "ap-northeast-1"
